import { GridLayout } from "grid-layout.slint";
import { Context, Function, Interface } from "../globals/prelude.slint";

export component GroupBox inherits Rectangle {
    in property <string> title;
    in property <int> index;
    in property <[Function]> functions;

    private property <length> padding-x: 50px;

    background: Interface.default-bg;

    VerticalLayout {
        spacing: 10px;
        alignment: start;

        VerticalLayout {  // title
            padding-left: padding-x;
            alignment: end;
            height: 30px;

            HorizontalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;

                Image {
                    source: @image-url("../icons/point.svg");
                    colorize: black;
                }

                Text {
                    horizontal-alignment: center;
                    text: root.title;
                    color: Interface.text-color;
                }
            }

            Rectangle {
                height: Interface.split-size;
                background: Interface.split-bg;
            }
        }

        GridLayout {
            functions: root.functions;
            index: root.index;
        }
    }

    changed height => {
        Context.goupbox-heights[index] = self.height;
        debug("index:", self.index, "height:", self.height);
    }
}
