import { QGridLayout } from "grid-layout.slint";
import { SubFunction, ComponentContext } from "../global.slint";

export component GroupBox inherits Rectangle {
    in property <string> name;
    in property <int> func-index;
    in property <[SubFunction]> sub-functions;

    private property <length> padding-x: 50px;

    background: ComponentContext.default-bg;

    VerticalLayout {
        spacing: 10px;
        alignment: start;

        VerticalLayout {  // title
            padding-left: padding-x;
            alignment: end;
            height: 30px;

            HorizontalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;

                Image {
                    source: @image-url("../icons/point.svg");
                    colorize: black;
                }

                Text {
                    horizontal-alignment: center;
                    text: root.name;
                    color: ComponentContext.text-color;
                }
            }

            Rectangle {
                height: ComponentContext.spliter.pix;
                background: ComponentContext.spliter.bg;
            }
        }

        QGridLayout {
            sub-functions: root.sub-functions;
            func-index: root.func-index;
        }
    }
}
