// the title on left
import { Settings } from "settings.slint";
import { UserInfo } from "userinfo.slint";
import { Context, Interface } from "../globals/prelude.slint";

export component NavItem inherits Rectangle {
    in property <int> index;
    in property <string> name;

    preferred-height: 40px;
//    background: #3661A9;
    border-radius: 8px;

    HorizontalLayout {
        alignment: center;
        spacing: 5px;
        icon := Image {
            source: @image-url("../icons/item.svg");
            colorize: Interface.text-color;
        }

        title := Text {
            text: root.name;
            color: Interface.text-color;
            vertical-alignment: center;
        }
    }

    states [
        active when Context.current-index == root.index: {
            root.background: #3661A9;
            title.color: Interface.none-bg;
            icon.colorize: Interface.none-bg;
        }
    ]

    TouchArea {
        mouse-cursor: pointer;

        clicked => {
            Context.update-index(root.index);
        }
    }
}

export component Navigation inherits Rectangle {
    preferred-width: 240px;
    background: Interface.default-bg;

    VerticalLayout {
        VerticalLayout {
            alignment: start;
            padding: 20px;
            spacing: 2px;

            for func[i] in Context.functions: NavItem {
                index: i;
                name: func.name;
            }
        }

        VerticalLayout {
            padding-left: 20px;
            padding-right: 20px;
            padding-bottom: 5px;
            alignment: end;
            settings := Settings {}
        }

        UserInfo {}
    }
}
