import { ComponentContext, SettingsContext } from "../global.slint";

component SettingButton inherits Rectangle {
    in property <string> name;
    in property <image> source;

    callback clicked();

    private property <length> padding-x: 10px;

    border-radius: 2px;
    preferred-height: 25px;

    HorizontalLayout {
        alignment: space-between;

        VerticalLayout {
            alignment: center;
            padding-left: padding-x;

            Text {
                horizontal-alignment: center;
                text: root.name;
                color: ComponentContext.text-color;
            }
        }

        VerticalLayout {
            alignment: center;
            padding-right: padding-x;

            Image {
                source: root.source;
//                colorize: ComponentContext.text-color;
            }
        }
    }

    TouchArea {
        mouse-cursor: pointer;
        clicked => {
            SettingsContext.update-visable();
            root.clicked();
        }
    }
}

export component Settings inherits Rectangle {
    visible: SettingsContext.visable;

    border-width: 1px;
    border-color: #efefef;

    VerticalLayout {
        alignment: center;
        padding-top: 5px;
        padding-bottom: 5px;
        spacing: 5px;

        SettingButton {
            name: @tr("Language");
            source: @image-url("../icons/chevron-right.svg");
            clicked => {
                // TODO
            }
        }

        Rectangle {
            height: ComponentContext.spliter.pix;
            background: ComponentContext.spliter.bg;
        }

        SettingButton {
            name: @tr("Upgrade");
            source: ComponentContext.upgradable ? @image-url("../icons/upgradable.svg") : @image-url("");
            clicked => {
                // TODO
            }
        }

        SettingButton {
            name: @tr("Connection Settings");
            source: @image-url("");
            clicked => {
                // TODO
            }
        }

        SettingButton {
            name: @tr("Update Password");
            source: @image-url("");
            clicked => {
                // TODO
            }
        }

        Rectangle {
            height: ComponentContext.spliter.pix;
            background: ComponentContext.spliter.bg;
        }

        SettingButton {
            name: @tr("Logout");
            source: @image-url("");
            clicked => {
                // TODO
            }
        }
    }
}
