import { ComponentContext, SettingsContext } from "../global.slint";

export component UserInfo inherits Rectangle {
    private property <length> font-size: 18px;

    border-width: 1px;
    border-color: #efefef;
    height: 50px;
    background: ComponentContext.default-bg;

    HorizontalLayout {
        spacing: 5px;
        padding: 5px;

        VerticalLayout {
            alignment: center;
            Rectangle {
                background: #3661A9;
                height: root.height / 2 + 8px;
                width: self.height;
                border-radius: self.width / 2;
                Text {
                    vertical-alignment: center;
                    text: ComponentContext.lastname;
                }
            }
        }

        VerticalLayout {
            alignment: center;
            spacing: 2px;

            Text {
                text: ComponentContext.username;
                font-weight: 600;
                color: ComponentContext.text-color;
                vertical-alignment: center;
                font-size: root.font-size;
                overflow: elide;
            }

            Text {
                text: ComponentContext.email;
                color: #8C8C8C;
                vertical-alignment: center;
                font-size: root.font-size / 2;
                overflow: elide;
            }
        }

        Rectangle {
            width: 30px;
            Image {
                source: @image-url("../icons/more.svg");
                height: root.height;
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    SettingsContext.update-visable();
                }
            }
        }
    }
}
