import { Context, Function, FunctionGroup } from "globals/prelude.slint";
import { MainWindow } from "windows/prelude.slint";

export { Context, Function, FunctionGroup }

export component AppWindow inherits Window {
    title: "Slint Demo";
//    icon: @image-url("app.svg");
    preferred-width: 1280px;
    preferred-height: 720px;
    default-font-size: 14px;

    main := MainWindow {
        height: root.height;
        width: root.width;
    }
}
