import { Navigation } from "components/navigation.slint";
import { GroupBox } from "components/group-box.slint";
import { ComponentContext } from "global.slint";
import { ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Slint Demo";
//    icon: @image-url("app.svg");
    preferred-width: 1280px;
    preferred-height: 720px;
    default-font-size: 14px;

    HorizontalLayout {
        Navigation {
            default-height: root.height;
            default-width: root.width / 8;
        }

        Rectangle {
            width: ComponentContext.spliter.pix;
            background: ComponentContext.spliter.bg;
        }

        ScrollView {
            viewport-height: root.height + 500px;   // TODO
            vertical-scrollbar-policy: always-off;

            Rectangle {
                preferred-width: (root.width / 8) * 7;
                preferred-height: root.height;
                background: ComponentContext.default-bg;

                VerticalLayout {
                    alignment: start;
                    padding-top: 20px;
                    for func in ComponentContext.functions: GroupBox {
                        name: func.name;
                        sub-functions: func.sub-func;
                    }
                }
            }
        }
    }
}
