import { Navigation } from "components/navigation.slint";
import { GroupBox } from "components/group-box.slint";
import { ComponentContext, FunctionContext, SubFunction, Function } from "global.slint";
import { ScrollView } from "std-widgets.slint";

export component Main inherits HorizontalLayout {
    Navigation {
        default-height: root.height;
        default-width: root.width / 8;
    }

    Rectangle {
        width: ComponentContext.spliter.pix;
        background: ComponentContext.spliter.bg;
    }

    ScrollView {    // 高度不匹配
        viewport-height: root.height + 350px;   // TODO
        vertical-scrollbar-policy: always-off;

        Rectangle {
            preferred-width: (root.width / 8) * 7;
            preferred-height: root.height;
            background: ComponentContext.default-bg;

            VerticalLayout {
                alignment: start;
                padding-top: 20px;
                for func[i] in FunctionContext.functions: GroupBox {
                    name: func.name;
                    func-index: i;
                    sub-functions: func.sub-func;
                }
            }
        }

        scrolled => {
            debug("viewport-y: ", self.viewport-y);
        }
    }
}
